### ISSUE TITLE
Calibre 5.0 compatibility

### ISSUE THREAD

**Issue by bdcaf** [bdcaf/calibre-crossref-doi-download#1]
First test gives error:

  ```
calibre, version 5.0.0
  FEHLER: Keine Übereinstimmungen gefunden: <p>Es wurden keine Bücher für die aktuelle Suche gefunden. Versuchen Sie, die Suche <b>weniger spezifisch</b> zu formulieren. Verwenden Sie beispielsweise nur den Nachnamen des Autors und ein einzelnes, prägnantes Wort aus dem Titel.<p>Um den gesamten Protokoll zu lesen, klicken Sie auf "Details anzeigen".

  Running identify query with parameters: 
  {'title': 'Exact Matrix Completion via Convex Optimization', 'authors': ['Candes, Emmanuel J.', 'Recht, Benjamin'], 'identifiers': {'zkey': 'YFQKXFA6', 'zkey_file': 'CANDESE_RECHTB'}, 'timeout': 30} 
  Using plugins: Crossref DOI Metadata Downloader (0, 0, 1) 
  The log from individual plugins is below 

  ****************************** Crossref DOI Metadata Downloader (0, 0, 1) ****************************** 
  Found 0 results 
  Downloading from Crossref DOI Metadata Downloader took 0.06382107734680176 
  start doi lookup
  email: XXXXX@XXXX.XX
  Plugin Crossref DOI Metadata Downloader failed
  Traceback (most recent call last):
    File "site-packages/calibre/ebooks/metadata/sources/identify.py", line 47, in run
    File "calibre_plugins.crossref_doi_download.__init__", line 84, in identify
  AttributeError: 'dict' object has no attribute 'has_key' 

  ******************************************************************************** 
  The identify phase took 0.21 seconds 
  The longest time (0.063821) was taken by: Crossref DOI Metadata Downloader 
  Merging results from different sources 
  We have 0 merged results, merging took: 0.00 seconds 
```

**Comment by bdcaf** [comment]
Ok - so far caught all "obvious" incompatibilities.
